name: Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  docs:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: echo "Generate docs ... 📚"

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: cw-member-join
          path: /home/runner/work/cw-member-join/cw-member-join
          retention-days: 7

  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"

      - name: Run grcov
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Codecov upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.coverage.outputs.report }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying ... 🚀"

      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: cw-member-join  

      - run: pwd && ls -la

